# Generated by Django 5.2.13 on 2026-04-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Digilib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(max_length=150)),
                ('tahun', models.IntegerField()),
                ('abstrak', models.TextField()),
                ('tautan_file', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(max_length=150)),
                ('tahun', models.IntegerField()),
                ('penerbit', models.CharField(max_length=150)),
                ('lokasi_rak', models.CharField(max_length=50)),
            ],
        ),
    ]
