# Generated by Django 5.2.13 on 2026-04-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digilib',
            name='fakultas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
