# Generated by Django 6.0.4 on 2026-04-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('date_release', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='digilib', max_length=50)),
                ('url_asli', models.URLField(max_length=500, unique=True)),
                ('diambil_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
