# Generated by Django 6.0.4 on 2026-04-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenakademik',
            name='tanggal_terbit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
