# Generated by Django 6.0.4 on 2026-05-13 04:09

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokumenakademik',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='dokumenakademik',
            old_name='diambil_pada',
            new_name='indexed_at',
        ),
        migrations.RemoveField(
            model_name='dokumenakademik',
            name='url_asli',
        ),
        migrations.AddField(
            model_name='dokumenakademik',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dokumenakademik',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumenakademik',
            name='identifier',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dokumenakademik',
            name='relation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumenakademik',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumenakademik',
            name='source_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumenakademik',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumenakademik',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dokumenakademik',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokumenakademik',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokumenakademik',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='dokumenakademik',
            table='SearchEngine_dokumenakademik',
        ),
    ]
