# Generated by Django 6.0.4 on 2026-05-17 09:50

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngine', '0002_searchtrend_alter_dokumenakademik_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dokumenakademik',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='SearchEngin_search__5181e3_gin'),
        ),
    ]
