# Generated by Django 6.0.4 on 2026-04-29 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngine', '0003_remove_dokumenakademik_tanggal_terbit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokumenakademik',
            options={'managed': False},
        ),
    ]
