# Generated by Django 5.2.13 on 2026-04-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngine', '0004_alter_dokumenakademik_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dokumenakademik',
            table='SearchEngine_dokumenakademik',
        ),
    ]
